# config.yaml

working-dir:  E:\project\pCR_paper_code
param-dir: results\intermediate\model_params
lr-dir: abc\results\intermediate\models
data-dir: results/intermediate/features.parquet
# Add more arguments as needed
